/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.layouts;

import controller.GUIController;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import view.main.JFrameMain;

/**
 *
 * @author Nikola
 */
public class JPanelTerminalLayout extends javax.swing.JPanel {

    /**
     * Creates new form JPanelTerminalLayout
     */
    public JPanelTerminalLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTerminal = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jTextAreaTerminal.setBackground(new java.awt.Color(0, 51, 51));
        jTextAreaTerminal.setColumns(20);
        jTextAreaTerminal.setForeground(new java.awt.Color(0, 204, 51));
        jTextAreaTerminal.setRows(5);
        jTextAreaTerminal.setSelectionColor(new java.awt.Color(0, 204, 51));
        jTextAreaTerminal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaTerminalKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaTerminal);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaTerminalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaTerminalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                int last = jTextAreaTerminal.getLineCount() - 1;
                int start = jTextAreaTerminal.getLineStartOffset(last);
                int end = jTextAreaTerminal.getLineEndOffset(last);

                String lastLine = jTextAreaTerminal.getText().substring(start, end);
                try {
                    GUIController.getController().performCommand(lastLine);
                } catch (URISyntaxException | IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error while executing operation", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jTextAreaTerminalKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaTerminal;
    // End of variables declaration//GEN-END:variables
}
