/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.main;

import view.layouts.JPanelTerminalLayout;
import controller.GUIController;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.BadLocationException;
import view.chat.JPanelChat;
import view.layouts.JPanelInterfaceLayout;
import view.settings.general.JPanelGeneralSettings;

/**
 *
 * @author Nikola
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem16 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTerminal = new javax.swing.JTextArea();
        jPanelSidebarLeft = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanelSidebarRight = new javax.swing.JPanel();
        jPanelFooter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPaneLayout = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem16.setText("jMenuItem16");

        jTextAreaTerminal.setBackground(new java.awt.Color(0, 51, 51));
        jTextAreaTerminal.setColumns(20);
        jTextAreaTerminal.setForeground(new java.awt.Color(0, 204, 51));
        jTextAreaTerminal.setRows(5);
        jTextAreaTerminal.setSelectionColor(new java.awt.Color(0, 204, 51));
        jTextAreaTerminal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaTerminalKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaTerminal);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 650));

        jPanelSidebarLeft.setPreferredSize(new java.awt.Dimension(200, 344));
        jPanelSidebarLeft.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(210, 322));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Bussiness Integration");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Local Chat");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Mark");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Peter");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Quick Start");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Facebook");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Twitter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("YouTube");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setToolTipText("");
        jScrollPane1.setViewportView(jTree1);

        jPanelSidebarLeft.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelSidebarLeft, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanelSidebarRightLayout = new javax.swing.GroupLayout(jPanelSidebarRight);
        jPanelSidebarRight.setLayout(jPanelSidebarRightLayout);
        jPanelSidebarRightLayout.setHorizontalGroup(
            jPanelSidebarRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelSidebarRightLayout.setVerticalGroup(
            jPanelSidebarRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSidebarRight, java.awt.BorderLayout.LINE_END);

        jLabel1.setText("Copyright 2016 - 2017, Social Network Integration");
        jPanelFooter.add(jLabel1);

        getContentPane().add(jPanelFooter, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jTabbedPaneLayout, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("New Project...");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/user-new.png"))); // NOI18N
        jMenuItem2.setText("New User...");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Import...");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Export...");
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator4);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/settings-icon.png"))); // NOI18N
        jMenuItem17.setText("Settings...");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem17);

        jMenuItem12.setText("Page Layout");
        jMenu1.add(jMenuItem12);
        jMenu1.add(jSeparator3);

        jMenuItem11.setText("Exit");
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Profile");

        jMenuItem19.setText("Bussines Chat");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/facebook-icon.png"))); // NOI18N
        jMenuItem6.setText("Facebook");
        jMenu3.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/twitter-icon.png"))); // NOI18N
        jMenuItem7.setText("Twitter");
        jMenu3.add(jMenuItem7);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/google-plus-icon.png"))); // NOI18N
        jMenuItem9.setText("Google+");
        jMenu3.add(jMenuItem9);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Instagram-icon.png"))); // NOI18N
        jMenuItem13.setText("Instagram");
        jMenu3.add(jMenuItem13);
        jMenu3.add(jSeparator2);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/linkedin-icon.png"))); // NOI18N
        jMenuItem8.setText("LinkedIn");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Settings");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Google Command");
        jCheckBoxMenuItem1.setToolTipText("If this property is selected, command from terminal that is not executable will preform google search.");
        jMenu5.add(jCheckBoxMenuItem1);
        jMenu5.add(jSeparator5);

        jMenuItem10.setText("User Settings...");
        jMenu5.add(jMenuItem10);

        jMenu6.setText("Network Settings");

        jMenuItem14.setText("Facebook...");
        jMenu6.add(jMenuItem14);

        jMenuItem15.setText("Twitter");
        jMenu6.add(jMenuItem15);

        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        jMenu4.setText("Help");

        jMenuItem18.setText("Report Issue");
        jMenu4.add(jMenuItem18);
        jMenu4.add(jSeparator6);

        jMenuItem5.setText("About");
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaTerminalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaTerminalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                int last = jTextAreaTerminal.getLineCount() - 1;
                int start = jTextAreaTerminal.getLineStartOffset(last);
                int end = jTextAreaTerminal.getLineEndOffset(last);

                String lastLine = jTextAreaTerminal.getText().substring(start, end);
                try {
                    GUIController.getController().performCommand(lastLine);
                } catch (URISyntaxException | IOException ex) {
                    JOptionPane.showMessageDialog(this, "Error while executing operation", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(JFrameMain.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jTextAreaTerminalKeyPressed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        JDialog dialog = new JDialog(this, "General Settings", Dialog.ModalityType.APPLICATION_MODAL);
        JPanel panel = new JPanelGeneralSettings();
        panel.setPreferredSize(new Dimension(520, 460));
        dialog.add(panel);
        dialog.setResizable(false);
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        JDialog dialog = new JDialog(this, "Bussines Chat", Dialog.ModalityType.MODELESS);
        JPanel panel = new JPanelChat();
        dialog.add(panel);
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelSidebarLeft;
    private javax.swing.JPanel jPanelSidebarRight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPaneLayout;
    private javax.swing.JTextArea jTextAreaTerminal;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        jTabbedPaneLayout.add("Terminal", new JPanelTerminalLayout());
        jTabbedPaneLayout.add("Start Page", new JPanelInterfaceLayout());
    }
}
